### PR TITLE
Rename bt_object to bt_value

### PR DESCRIPTION
**Pull request by eepp**

### CODE REVIEW

**Comment by jgalar** [comment]
There is a missing rename here, I have edited the commit on my end.
https://github.com/efficios/babeltrace/blob/master/tests/tests#L6

**Comment by eepp** [comment]
> There is a missing rename here, I have edited the commit on my end.

Please accept my sincere apologies for the mistake.

**Comment by jgalar** [comment]
k.

**Comment by jgalar** [comment]
Merged, thanks!

**Pull request closed without merging**
