### PR TITLE
CTF IR: consolidate reference counting functions

### PR DESCRIPTION
**Pull request by eepp**
See commit msg of 79b2450.

Valgrind reports 0 leaks when running `test_ctf_writer` after having merged this PR :ok_hand:.

### CODE REVIEW

**Comment by jgalar** [comment]
Good idea, but let's take the opportunity to define a base "class" for all BT objects (basically, IR and bt_object) along with documentation stating that this class _must_ be the first member of subclasses.

**Comment by eepp** [comment]
Updated.

**Comment by jgalar** [comment]
The latest patch set doesn't pass tests
```
ok 1 - BT_OBJECT_PUT() resets the variable to NULL
ok 2 - BT_OBJECT_MOVE() resets the source variable to NULL
ok 3 - BT_OBJECT_MOVE() moves the ownership
ok 4 - bt_object_freeze() fails with an object set to NULL
ok 5 - bt_object_freeze() succeeds with a null object
ok 6 - NULL is not frozen
ok 7 - the null singleton is frozen
ok 8 - bt_object_is_frozen() returns false with a fresh object
ok 9 - bt_object_freeze() passes with a frozen object
ok 10 - bt_object_is_frozen() returns true with a frozen object
ok 11 - bt_object_null is not NULL
ok 12 - bt_object_null is a null object
ok 13 - getting bt_object_null does not cause a crash
lt-test_bt_objects: ../include/babeltrace/ref-internal.h:61: bt_ref_put: Assertion `ref->release_func' failed.
```

**Comment by jgalar** [comment]
Merged in master, thanks!

**Pull request closed without merging**
